### PR TITLE
update license to BSD-3-Clause

### PR DESCRIPTION
**Pull request by andreeaflorescu**
As per the discussion in: https://github.com/rust-vmm/vmm-sys-util/issues/161

Before merging this, please wait for approvals from stakeholders:
- Intel
- Alibaba
- Red Hat
- Other?

### Summary of the PR

*Please summarize here why the changes in this PR are needed.*

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Review by rbradford — APPROVED** [review]

**Review by stefano-garzarella — DISMISSED** [review]

**Review by jiangliu — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
@bonzini @haraldh I approved this PR for Red Hat changes.
Would be nice if we can have an ack from you since you contributed on this crate.

**Review by haraldh — DISMISSED** [review]
`LICENSE-APACHE` got removed ... does it need a new LICENSE file then?

**Comment by stefano-garzarella** [comment]
> `LICENSE-APACHE` got removed ... does it need a new LICENSE file then?

@haraldh `LICENSE-BSD-3-Clause` is remaining in the repo, so IIUC it should be fine.

**Comment by andreeaflorescu** [comment]
I had to do a rebase to fix the conflicts, @jiangliu @rbradford @stefano-garzarella @haraldh can you re-approve. Thanks!

**Review by haraldh — APPROVED** [review]

**Review by jiangliu — APPROVED** [review]

**Review by rbradford — APPROVED** [review]

**Pull request merged**
